# Generated by Django 2.2.6 on 2019-11-20 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0002_auto_20191120_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpassword',
            name='pwd_creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pwdcreator_user_details', to='credentials.Users'),
        ),
        migrations.AlterField(
            model_name='usersdetails',
            name='details_creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dtlcreator_user_details', to='credentials.Users'),
        ),
    ]
