# Generated by Django 2.2.6 on 2019-11-20 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0004_auto_20191120_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersdetails',
            name='details_creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='dtlcreator_user_details', to='credentials.Users'),
        ),
        migrations.AlterField(
            model_name='usersdetails',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='id_user_details', to='credentials.Users'),
        ),
    ]
