# Generated by Django 2.2.6 on 2019-11-20 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0005_auto_20191121_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userspasswords',
            name='pwd_creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pwdcreator_user_details', to='credentials.Users'),
        ),
        migrations.AlterField(
            model_name='userspasswords',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='id_user_password', to='credentials.Users'),
        ),
    ]
